#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE23B7E70B467F0BF (office@who-t.net)
#
Name     : libXext
Version  : 1.3.3
Release  : 13
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXext-1.3.3.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXext-1.3.3.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/lib/libXext-1.3.3.tar.gz.sig
Summary  : Misc X Extension Library
Group    : Development/Tools
License  : MIT-Opengroup
Requires: libXext-lib
Requires: libXext-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xextproto)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
BuildRequires : xmlto

%description
libXext - library for common extensions to the X11 protocol
No new extensions should be added to this library - it is now instead
preferred to make per-extension libraries that can be evolved as needed
without breaking compatibility of this core library.

%package dev
Summary: dev components for the libXext package.
Group: Development
Requires: libXext-lib
Provides: libXext-devel

%description dev
dev components for the libXext package.


%package dev32
Summary: dev32 components for the libXext package.
Group: Default
Requires: libXext-lib32
Requires: libXext-dev

%description dev32
dev32 components for the libXext package.


%package doc
Summary: doc components for the libXext package.
Group: Documentation

%description doc
doc components for the libXext package.


%package lib
Summary: lib components for the libXext package.
Group: Libraries

%description lib
lib components for the libXext package.


%package lib32
Summary: lib32 components for the libXext package.
Group: Default

%description lib32
lib32 components for the libXext package.


%prep
%setup -q -n libXext-1.3.3
pushd ..
cp -a libXext-1.3.3 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492279154
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto "
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1492279154
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/MITMisc.h
/usr/include/X11/extensions/XEVI.h
/usr/include/X11/extensions/XLbx.h
/usr/include/X11/extensions/XShm.h
/usr/include/X11/extensions/Xag.h
/usr/include/X11/extensions/Xcup.h
/usr/include/X11/extensions/Xdbe.h
/usr/include/X11/extensions/Xext.h
/usr/include/X11/extensions/Xge.h
/usr/include/X11/extensions/dpms.h
/usr/include/X11/extensions/extutil.h
/usr/include/X11/extensions/multibuf.h
/usr/include/X11/extensions/security.h
/usr/include/X11/extensions/shape.h
/usr/include/X11/extensions/sync.h
/usr/include/X11/extensions/xtestext1.h
/usr/lib64/libXext.so
/usr/lib64/pkgconfig/xext.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXext.so
/usr/lib32/pkgconfig/32xext.pc
/usr/lib32/pkgconfig/xext.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libXext/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXext.so.6
/usr/lib64/libXext.so.6.4.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXext.so.6
/usr/lib32/libXext.so.6.4.0
