#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXext
Version  : 1.3.3
Release  : 4
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXext-1.3.3.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXext-1.3.3.tar.gz
Summary  : Misc X Extension Library
Group    : Development/Tools
License  : MIT-Opengroup
Requires: libXext-lib
Requires: libXext-doc
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
BuildRequires : xmlto

%description
libXext - library for common extensions to the X11 protocol
No new extensions should be added to this library - it is now instead
preferred to make per-extension libraries that can be evolved as needed
without breaking compatibility of this core library.

%package dev
Summary: dev components for the libXext package.
Group: Development
Requires: libXext-lib

%description dev
dev components for the libXext package.


%package doc
Summary: doc components for the libXext package.
Group: Documentation

%description doc
doc components for the libXext package.


%package lib
Summary: lib components for the libXext package.
Group: Libraries

%description lib
lib components for the libXext package.


%prep
%setup -q -n libXext-1.3.3

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/MITMisc.h
/usr/include/X11/extensions/XEVI.h
/usr/include/X11/extensions/XLbx.h
/usr/include/X11/extensions/XShm.h
/usr/include/X11/extensions/Xag.h
/usr/include/X11/extensions/Xcup.h
/usr/include/X11/extensions/Xdbe.h
/usr/include/X11/extensions/Xext.h
/usr/include/X11/extensions/Xge.h
/usr/include/X11/extensions/dpms.h
/usr/include/X11/extensions/extutil.h
/usr/include/X11/extensions/multibuf.h
/usr/include/X11/extensions/security.h
/usr/include/X11/extensions/shape.h
/usr/include/X11/extensions/sync.h
/usr/include/X11/extensions/xtestext1.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libXext/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
